### ISSUE TITLE
Add Beer Information

### ISSUE THREAD

**Issue by ekubacki** [chrisjm/openbrewerydb-api-server#12]
Would you consider expanding the scope of this project to include beer information as well?

Example User Scenario:
As an API user, I want to be able to query by beer names and optionally brewery information to return information like: 
- The Brewery 
    - name: ,
    - brewery_type: ,
    - street: ,
    - city: ,
    - state: ,
    - postal_code: ,
    - country: ,
    - longitude: ,
    - latitude: ,
    - phone: ,
    - website_url: ,
    - updated_at: ,
    - tag_list: []
- The beer
    - beer_name: ,
    - beer_style: "",
    - beer_abv: ,
    - pDev:  ,
    - tasting_notes: ,
    - description: ,
    - breweryId : (or name?)

**Comment by chrisjm** [comment]
Hi, @ekubacki!

Thank you for this question!

At this time, I consider beer information to be out of scope for this particular project for a few reasons: 

1. Brewery data is public information (assuming the brewery wants to be visited). Beer information is in more of a grey area.
2. There are other APIs and databases out there that handle beer information, namely [BreweryDB](https://brewerydb.com/) and [Untappd](https://untappd.com/api/register).
3. Keeping beer information up to date is a monstrous task given it's changing daily/hourly. This is the main reason the APIs above limit/charge for it. It requires money and time investment from staff and community.
4. Storage costs. While there's a finite number of breweries in existence (in the 1000s), the number of beers is significantly larger.

That all said, I welcome further discussion on this.

🍻

**Comment by ekubacki** [comment]
That's fair.  Thanks for the fast response and suggestions!  Great project btw!
